language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: andrewcreegan
  password:
    secure: HEf+9iYOhN3xupkTcP8VWlLe1KOo16dkoEw6Schlxjc8/7Ti826UivwCyFxGEHKcuUXpQPQ7AlFQ4lx9HmJz0A8jxLGF/lGplrm0pPIhjoLD0q8I8duo8FskLkakOX4DkcrZY/2rk4zxkyVY2Pr77HSExhg+CbK5gq3UBYsfrJjQr0hnI4YYdH0o5bYrpj10izCneVJXdJ84c8n12OsJ2LCjtlChn9xpZSBUEjetRoaCI2jVGDr59UkvJVfTjSnu5ewRXbunkqQyo7sbPfI/TSVV4LZJdqqwpd9ocBpnOX7jzOcWyfWbvLnG8zVSOn3BtllMyUmjUtdKSEE5+4ymAjgLvytoxl1soJlf1+cRD6a545wuQmaUmozOd1hNNe6JBtm1TKVsjWJF7oDUkui4QO/rk1kuKOFw2cDCSqqMrtVaI4IZBZFQqbzfWCqAY1lsKc/R+4BQorBgzylzAXRqTi7+Qh8hJjSebDFY8KAy3wBp6VirUooFg9RHCSb9d/NFyi2jjM8SvoPa/bHn7O8C6NiCaqdc5MyUf42p0iAM8J2f5iuKUFdPIWnvfKsaKmGlZo8Zg1EnY42JVpi73KFniJWik3wN1QrsxO1ZbHPRyWWgjfyk8AONIInjTuvppsacEdlmC0JHJHCKkCteILqCH4AqhRsdiB57H4Y6yh6PGRY=
  on:
    tags: true
    repo: acreegan/adv_prodcon
    python: 3.8
