language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: andrewcreegan
  password:
    secure: BUuy1Tfdk7S1StRVgsXb1Ng1Ykt3At4Eikgk0hhyBMGLjj0WUbbf3rsgnsI1PqYDnmyxQluyRqgU58UI1XKN7eg9kadmUyeJBXovx1k4hv0g7dqA6Jv+GuFmXxP1Olc/ifblWZgq1SNavwpCMtVNn0cq37WLkVyfMoByKuRXiE/Fm38af1iuIATPiIJi9FCv3fUAk4X6mYOOsIfk34De5CuG9fAbhTJQ/2X7DJMPGvAs9mkWTcEbw360NydyEzTBzKCq4yfslZDNlb05j5N7ZrxRGquadUUBgzL9tmE1+X0IkX9d5P9UbtAmm6GV7Z0Nb3fMGGfUf4RWIEtRVpXEgXFQCut1dmL8RoogCt7fRVcbIWWoLdJcKn8StXsR2sJgULux8xp3DyiSWkMKZ8beX7PYFv830bD6ENQbfQIgmRw6jYv8K6E30t0wwLPpP4dRYNLrz8Jn27NEFp6Ta0uvoeF7z6O31ebzhxSdRCdGr2iNonFqh9GT9hJwBoyIjE4HUixaPsVWQyqdyPgI+9q0Fxibl4a/Sw6viUWX7xW5GJubiaHXBX3+pJSbY0dbNXJx7sfnrC/h7qslZdv4Psb7dTXQMBANBBXRxF3rF5H+retWM1hU3y8hGVjkG2qLotFtbfCHw+H2wP4WZplInHrGhy0b7RLXfKtLpPXV4vVtjfU=
  on:
    tags: true
    repo: acreegan/adv_prodcon
    python: 3.8
